// prettier-ignore
const testCases = [
  [['bca', 'aaa', 'acb'], ['b', 'a', 'c']],
  [['acbc', 'bcc', 'bcb', 'ba'], ['c', 'a', 'b']],
  [['aba', 'bac', 'baa', 'bbcb', 'bbbc'], ['c', 'a', 'b']],
  [['baa', 'bac', 'aaa'], ['b', 'a', 'c']],
  [['cbab', 'cbba', 'acc', 'acb'], ['c', 'a', 'b']],
  [['abb', 'abc', 'bab', 'bac', 'cbc'], ['a', 'b', 'c']],
  [['dfe', 'def', 'efd', 'eff'], ['d', 'f', 'e']],
  [['eff', 'efd', 'ddf', 'dde'], ['f', 'e', 'd']],
  [['fee', 'fed', 'eed', 'edf'], ['f', 'e', 'd']],
  [['nmm', 'mno', 'mon', 'onmm', 'onmo'], ["n", "m", "o"]],
  [['onn', 'ono', 'mnon', 'mnom'], ["n", "o", "m"]],
  [['nmnm', 'nmnn', 'onmm', 'onnn'], ["m", "n", "o"]],
  [['trop', 'trot', 'tort', 'rtr', 'rto'], ['p', 't', 'r', 'o']],
  [['gtio', 'gtig', 'tti', 'ito'], ['o', 'g', 't', 'i']],
  [['adcb', 'adb', 'dacb', 'ddbc', 'cbcd'], ['a', 'd', 'c', 'b']],
  [['ghrr', 'hgrq', 'hgqh', 'rghg', 'rghq', 'qrrh'], ['g', 'h', 'r', 'q']],
  [['vhre', 'vhrh', 'rher', 'ervh', 'eerh'], ['v', 'r', 'e', 'h']],
  [['qmhp', 'qmpq', 'mhqq', 'mqh', 'phpm'], ['h', 'q', 'm', 'p']],
  [['bnotr', 'bntr', 'ottb', 'rnbt', 'rtbb', 'rtbn', 'nbtr', 'tbnt'], ['b', 'o', 'r', 'n', 't']],
  [['vretp', 'vrptr', 'rptvr', 'rpter', 'erpt', 'ptrvr', 'tvr'], ['v', 'r', 'e', 'p', 't']],
  [['ghrws', 'ghrs', 'wwhrg', 'hrs', 'srghs', 'srgs', 'rshr', 'rrhr'], ['g', 'w', 'h', 's', 'r']],
  [['gyrew', 'gyer', 'yerw', 'yere', 'rygr', 'wrger', 'erer'], ['g', 'y', 'r', 'w', 'e']],
  [['jkrwq', 'kjrw', 'kjwq', 'wkjq', 'wkjr', 'wkjj'], ['q', 'r', 'j', 'k', 'w']],
  [['fdwrt', 'fdrtr', 'trdff', 'trtdf', 'trwdf', 'wrtfr', 'wrtdf', 'rtdd', 'rtrdf'], ['f', 'd', 't', 'w', 'r']],
  [['mmks', 'mnjkws', 'mnkww', 'jwksn', 'jsjnm', 'jssjn', 'wjsnm', 'kwnjs', 'kwnks', 'kwnnj', 'knjj', 'swwsmn', 'nswkj'], ['m', 'j', 'w', 'k', 's', 'n']],
  [['gyqo', 'qpqwo', 'pqqwo', 'wpyo', 'ypowq', 'ypoow', 'oyqw'], ['g', 'q', 'p', 'w', 'y', 'o']],
  [['trpoi', 'pori', 'poupo', 'riout', 'rioiu', 'iopto', 'otrpo'], ['t', 'p', 'r', 'u', 'i', 'o']],
  [['ghion', 'ghonn', 'hioun', 'higho', 'noign', 'nognh', 'uhno'], ['i', 'o', 'g', 'h', 'n', 'u']],
  [['nbvowq', 'nbwqo', 'nvqo', 'qboo', 'ovbo', 'bnoqo'], ['n', 'q', 'o', 'b', 'v', 'w']],
  [['jklrow', 'klorw', 'kljow', 'rwokj', 'rwolj', 'lkjow', 'worl'], ['o', 'j', 'k', 'r', 'l', 'w']],
]

// prettier-ignore
const invalidTestCases = [
  [['aaa', 'acb', 'bca'], []],
  [['bcb', 'acbc', 'bcc', 'ba'],[]],
  [['bbcb', 'bac', 'baa', 'aba', 'bbbc'], []],
  [['bac', 'aaa', 'baa'], []],
  [['acc', 'cbab', 'cbba', 'acb'], []],
  [['bac', 'abc', 'bab', 'abb', 'cbc'], []],
  [['efd', 'def', 'dfe', 'eff'], []],
  [['ddf', 'dde', 'efd', 'eff', 'fee'], []],
  [['eed', 'edf', 'fed', 'fee', 'feed'], []],
  [['nmm', 'onmo', 'mon', 'onmm', 'mno'], []],
  [['onn', 'mnom', 'mnon', 'ono'], []],
  [['nmnm', 'onnn', 'onmm', 'nmnn'], []],
  [['trop', 'rto', 'tort', 'rtr', 'trot'], []],
  [['gtio', 'ito', 'tti', 'gtig'], []],
  [['adcb', 'adb', 'cbcd', 'ddbc', 'dacb'], []],
  [['ghrr', 'hgrq', 'qrrh', 'rghg', 'hgqh', 'rghq'], []],
  [['vhre', 'eerh', 'rher', 'ervh', 'vhrh'], []],
  [['qmhp', 'phpm', 'mhqq', 'qmpq', 'mqh'], []],
  [['bnotr', 'bntr', 'ottb', 'tbnt', 'rtbb', 'rtbn', 'nbtr', 'rnbt'], []],
  [['vretp', 'vrptr', 'tvr', 'rpter', 'erpt', 'rptvr', 'ptrvr'], []],
  [['srgs', 'rrhr', 'ghrs', 'hrs', 'srghs', 'ghrws', 'rshr', 'wwhrg'], []],
  [['gyrew', 'gyer', 'yerw', 'yere', 'erer', 'wrger', 'rygr'], []],
  [['jkrwq', 'wkjj', 'kjwq', 'wkjq', 'wkjr', 'kjrw'], []],
  [['fdwrt', 'fdrtr', 'wrtdf', 'trtdf', 'trwdf', 'wrtfr', 'trdff', 'rtdd', 'rtrdf'], []],
  [['mmks', 'mnjkws', 'kwnjs', 'jwksn', 'kwnnj', 'jssjn', 'wjsnm', 'mnkww', 'kwnks', 'jsjnm', 'knjj', 'swwsmn', 'nswkj'], []],
  [['gyqo', 'qpqwo', 'oyqw', 'wpyo', 'ypowq', 'ypoow', 'pqqwo'], []],
  [['trpoi', 'pori', 'iopto', 'riout', 'rioiu', 'poupo', 'otrpo'], []],
  [['ghion', 'ghonn', 'hioun', 'uhno', 'noign', 'nognh', 'higho'], []],
  [['nbvowq', 'ovbo', 'nvqo', 'qboo', 'nbwqo', 'bnoqo'], []],
  [['jklrow', 'lkjow', 'kljow', 'rwokj', 'rwolj', 'klorw', 'worl'], []]
]

module.exports = { testCases, invalidTestCases }
